enhance dyff comment

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -161,42 +161,58 @@ jobs:
       shell: bash
       run: |
         echo "output_dir=$RUNNER_TEMP" | tee -a "$GITHUB_OUTPUT"
-        templates_files=$(find "$RUNNER_TEMP/old" "$RUNNER_TEMP/new" -maxdepth 2 -name '*.yaml' | sed -E 's|'"$RUNNER_TEMP"'/(old\|new)/||' | sort | uniq)
-
+        values_directories=$(find "$RUNNER_TEMP/old" "$RUNNER_TEMP/new" -maxdepth 1 -type d | sed -E 's|'"$RUNNER_TEMP"'/(old\|new)||' | sed -E 's|^/||' | sort | uniq)
         header="# dyff of changes in rendered templates of CI manifests\n\n"
         comment_body=""
-        while read -r templates_file; do
-          if [[ "$(basename "$templates_file")" == ".yaml" ]] && [ ! -s "$template_file" ]; then
+        while read -r values_dir; do
+          if [ -z "$values_dir" ]; then
             continue
           fi
 
-          if [ ! -f "$RUNNER_TEMP/old/$templates_file" ]; then
-            file_content=$(sed -e 's/^/+ /' < "$RUNNER_TEMP/new/$templates_file")
-            comment_body+="<details><summary><b>$templates_file</b> (added)</summary>\n"
-            comment_body+='\n```diff\n'
-            comment_body+=$file_content
-            comment_body+='\n```\n</details>\n\n'
-            continue
+          templates_files=$(find "$RUNNER_TEMP/old/$values_dir" "$RUNNER_TEMP/new/$values_dir" -maxdepth 1 -name '*.yaml' | sed -E 's|'"$RUNNER_TEMP"'/(old\|new)/||' | sort | uniq)
+          if [ "$templates_files" != "" ]; then
+              comment_body+="<details><summary><b>$values_dir.yaml</b></summary>\n"
           fi
 
-          if [ ! -f "$RUNNER_TEMP/new/$templates_file" ]; then
-            comment_body+="**$templates_file** (removed)\n\n"
-            continue
-          fi
-
-          exit_code=0
-          dyff_detail=$(dyff between --set-exit-code --omit-header --output=github "$RUNNER_TEMP/old/$templates_file" "$RUNNER_TEMP/new/$templates_file" 2>&1) || exit_code=$?
-          if [ $exit_code -ne 0 ]; then
-            if [[ "$dyff_detail" == *"failed to compare input files"* ]]; then
-              echo "failed with file $templates_file"
-              exit 1
+          while read -r templates_file; do
+            current_file="$(basename "$templates_file")"
+            if [[ "$current_file" == ".yaml" ]] && [ ! -s "$template_file" ]; then
+              continue
             fi
-            comment_body+="<details><summary><b>$templates_file</b> (changed)</summary>\n"
-            comment_body+='\n```diff\n'
-            comment_body+=$dyff_detail
-            comment_body+='\n```\n</details>\n\n'
+
+            if [ ! -f "$RUNNER_TEMP/old/$templates_file" ]; then
+              file_content=$(sed -e 's/^/+ /' < "$RUNNER_TEMP/new/$templates_file")
+              comment_body+="<details><summary>$current_file (added)</summary>\n"
+              comment_body+='\n```diff\n'
+              comment_body+=$file_content
+              comment_body+='\n```\n</details>\n\n'
+              continue
+            fi
+
+            if [ ! -f "$RUNNER_TEMP/new/$templates_file" ]; then
+              comment_body+="**$current_file** (removed)\n\n"
+              continue
+            fi
+
+            exit_code=0
+            dyff_detail=$(dyff between --set-exit-code --omit-header --output=github "$RUNNER_TEMP/old/$templates_file" "$RUNNER_TEMP/new/$templates_file" 2>&1) || exit_code=$?
+            if [ $exit_code -ne 0 ]; then
+              if [[ "$dyff_detail" == *"failed to compare input files"* ]]; then
+                echo "failed with file $templates_file"
+                exit 1
+              fi
+              comment_body+="<details><summary>$current_file (changed)</summary>\n"
+              comment_body+='\n```diff\n'
+              comment_body+=$dyff_detail
+              comment_body+='\n```\n</details>\n\n'
+            fi
+          done <<< "$templates_files"
+
+          if [ "$templates_files" != "" ]; then
+              comment_body+="---\n</details>\n"
           fi
-        done <<< "$templates_files"
+
+        done <<< "$values_directories"
 
         if [ -z "$comment_body" ]; then
           comment_body="No changes in rendered templates"
