ci: upload dyff generated manifests

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -114,11 +114,13 @@ jobs:
         mkdir -p "$RUNNER_TEMP/new"
         for values in charts/matrix-stack/ci/*values.yaml; do
           echo "Generating new templates with $values";
+          mkdir -p "$RUNNER_TEMP/new/$(basename "$values" ".yaml")"
           helm template \
               -n ess-ci \
               -a monitoring.coreos.com/v1/ServiceMonitor \
               -f "$values" charts/matrix-stack | \
-          yq ea '[.] | sort_by(.kind, .metadata.name) | .[] | splitDoc' > "$RUNNER_TEMP/new/$(basename "$values")"
+          yq ea '[.] | .[] | splitDoc' | \
+          yq -s "\"$RUNNER_TEMP/new/$(basename "$values" ".yaml")/\""' + ([.kind, .metadata.name] | join("-") | downcase) + ".yaml"'
         done
 
     # We want the most recent common ancestor between the target & PR branches rather than the target branch itself
@@ -139,11 +141,13 @@ jobs:
         mkdir -p "$RUNNER_TEMP/old"
         for values in charts/matrix-stack/ci/*values.yaml; do
           echo "Generating old templates with $values";
+          mkdir -p "$RUNNER_TEMP/old/$(basename "$values" ".yaml")"
           helm template \
               -n ess-ci \
               -a monitoring.coreos.com/v1/ServiceMonitor \
               -f "$values" charts/matrix-stack | \
-          yq ea '[.] | sort_by(.kind, .metadata.name) | .[] | splitDoc' > "$RUNNER_TEMP/old/$(basename "$values")"
+          yq ea '[.] | .[] | splitDoc' | \
+          yq -s "\"$RUNNER_TEMP/old/$(basename "$values" ".yaml")/\""' + ([.kind, .metadata.name] | join("-") | downcase) + ".yaml"'
         done
 
     - name: Install dyff with asdf
@@ -156,13 +160,23 @@ jobs:
       id: dyff
       shell: bash
       run: |
-        templates_files=$(find "$RUNNER_TEMP/old" "$RUNNER_TEMP/new" -maxdepth 1 -name '*values.yaml' | sed -E 's|'"$RUNNER_TEMP"'/(old\|new)/||' | sort | uniq)
+        echo "output_dir=$RUNNER_TEMP" | tee -a "$GITHUB_OUTPUT"
+        templates_files=$(find "$RUNNER_TEMP/old" "$RUNNER_TEMP/new" -maxdepth 2 -name '*.yaml' | sed -E 's|'"$RUNNER_TEMP"'/(old\|new)/||' | sort | uniq)
 
         header="# dyff of changes in rendered templates of CI manifests\n\n"
         comment_body=""
         while read -r templates_file; do
+          if [[ "$(basename "$templates_file")" == ".yaml" ]]; then
+            echo "skipping empty file"
+            continue
+          fi
+
           if [ ! -f "$RUNNER_TEMP/old/$templates_file" ]; then
-            comment_body+="**$templates_file** (added)\n\n"
+            file_content=$(cat "$RUNNER_TEMP/new/$templates_file")
+            comment_body+="<details><summary><b>$templates_file</b> (added)</summary>\n"
+            comment_body+='\n```diff\n'
+            comment_body+=$file_content
+            comment_body+='\n```\n</details>\n\n'
             continue
           fi
 
@@ -172,8 +186,12 @@ jobs:
           fi
 
           exit_code=0
-          dyff_detail=$(dyff between --set-exit-code --omit-header --output=github "$RUNNER_TEMP/old/$templates_file" "$RUNNER_TEMP/new/$templates_file") || exit_code=$?
+          dyff_detail=$(dyff between --set-exit-code --omit-header --output=github "$RUNNER_TEMP/old/$templates_file" "$RUNNER_TEMP/new/$templates_file" 2>&1) || exit_code=$?
           if [ $exit_code -ne 0 ]; then
+            if [[ "$dyff_detail" == *"failed to compare input files"* ]]; then
+              echo "failed with file $templates_file"
+              exit 1
+            fi
             comment_body+="<details><summary><b>$templates_file</b> (changed)</summary>\n"
             comment_body+='\n```diff\n'
             comment_body+=$dyff_detail
@@ -186,6 +204,13 @@ jobs:
         fi
 
         echo -e "$header$comment_body" | tee "$RUNNER_TEMP/dyff-output"
+
+    - name: Upload generated manifests
+      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
+      with:
+        name: dyff-templates
+        path: ${{ steps.dyff.outputs.output_dir }}
+        retention-days: 1
 
     - name: Find dyff comment
       if: github.event.pull_request.number != ''
