ci: check copyright dates

diff --git a/.github/workflows/licensing.yml b/.github/workflows/licensing.yml
--- a/.github/workflows/licensing.yml
+++ b/.github/workflows/licensing.yml
@@ -40,3 +40,47 @@ jobs:
         git config --global --add safe.directory "$GITHUB_WORKSPACE"
         reuse --version
         reuse spdx | ./scripts/spdx_checks.py
+
+    - name: Copyright dates
+      env:
+        BASE_REF: ${{ github.event.pull_request.base.sha }}
+      run: |
+        echo "Comparing $BASE_REF against current branch HEAD (`git rev-parse HEAD`)"
+        error_flag="false"
+
+        # Get the list of changed files
+        changed_files=$(git diff --diff-filter=rd --name-only $BASE_REF...HEAD)
+        copyright_year_now=$(date +%Y)
+        # Function to check if the copyright header is present in the file
+        # We ignore files without copyrights as we only want to check if the copyright is correct
+        # The check-enterprise-licensing job will verify that all files are copyrighted
+        has_copyright_header() {
+            file=$1
+            head -n 5 $file | grep -q "Copyright"
+        }
+        # Function to check if the copyright header is present with the correct date
+        check_copyright_header() {
+            file=$1
+            head -n 5 $file | grep -qE "Copyright $2" $file
+        }
+
+        echo "Changed files to verify : $changed_files"
+        # Loop through each changed file
+        for file in $changed_files; do
+            if [ -e $file ]; then
+                if has_copyright_header $file && ! check_copyright_header $file $copyright_year_now  && ! check_copyright_header $file "20[0-9]{2}-$COPYRIGHT_YEAR_NOW"; then
+                    echo "Copyright header not found or incorrect in $file"
+                    error_flag="true"
+                fi
+            else
+              echo "$file was removed"
+            fi
+        done
+
+        if [[ "$error_flag" == "true" ]]; then
+          echo "errors happened"
+          exit 1
+        else
+          echo "no errors"
+          exit 0
+        fi
